version: '3.4'
services:
  postgres:
    image: postgres:latest
    container_name: finnair-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
